### ISSUE TITLE
Necessary corrections to install.sh

### ISSUE THREAD

**Issue by arifer612** [cleder/login-picture#1]
Hi there, I saw your post from the howdy issues and was interested in having a script run on login to take a snapshot. I read through your code and noticed that there were a few mistakes that may need some corrections to work the way it is intended.

In `install.sh`, line 4:
https://github.com/cleder/login-picture/blob/c053f70cc882449532a7777f933d24d950fc3eaf/install.sh#L4

I believe you are trying to have pip updated to the latest version. If that is the case, the command should be 

    python3 -m pip install --upgrade pip

Line 9:
https://github.com/cleder/login-picture/blob/c053f70cc882449532a7777f933d24d950fc3eaf/install.sh#L9

I understand what the intention of this line is: to use the python binary in the virtual environment to run the script. However, I believe you also need to source the virtual environment before doing so. Otherwise, this virtual environment's path would not be sourced when running the script, making the `pip install`'s above without irrelevant to the execution.

Lastly, a suggestion: Placing the executable in `.local/bin` without the `.sh` extension would allow it to be executed from the command line without needing the exact path. This is, of course, unnecessary if you're just going to use it to run on log-in, but I'm just putting out there.

Once again, you had a very good idea and wrote up a nice short script!

**Comment by cleder** [comment]
Thanks :-).

`install.sh` line 4: this works as is because the virtual environment is activated the line before.

`install.sh` line 9:This works as is, the python will pick up its environment (see https://virtualenv.pypa.io/en/latest/user_guide.html#activators for an explanation), 
try without activating the virtual env:

```
python3 detcap.py 
Traceback (most recent call last):
  File "detcap.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

vs 

```
 ./venv/bin/python detcap.py 
```

**Comment by cleder** [comment]
The `~/.local` is not in the PATH environment any more with ubuntu 20.04 Focal Fossa
